boyt/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path
from videos import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name="home"),
    path('dashboard', views.dashboard, name="dashboard"),

    #Auth
    path('signup', views.SignUp.as_view(), name="signup"),
    path('login', auth_views.LoginView.as_view(), name="login"),
    path('logout', auth_views.LogoutView.as_view(), name="logout"),
    #Rows
    path('row/create', views.CreateRow.as_view(), name="create_row"),
    path('row/<int:pk>', views.DetailRow.as_view(), name="detail_row"),
    path('row/<int:pk>/delete', views.DeleteRow.as_view(), name="delete_row"),
    path('row/<int:pk>/update', views.UpdateRow.as_view(), name="update_row"),
    #Videos
    path('movie/<int:pk>/delete', views.DeleteMovie.as_view(), name="delete_movie"),
    path('row/<int:pk>/addmovie', views.add_movie, name="add_movie"),
    path('movie/search', views.movie_search, name="movie_search"),

]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

videos/models.py
from django.contrib.auth.models import User
from django.db import models


class Row(models.Model):
    title = models.CharField(max_length=255)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title


class Movies(models.Model):
    title = models.CharField(max_length=255)
    url = models.URLField()
    youtube_id = models.CharField(max_length=255)
    row = models.ForeignKey(Row, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

videos/forms.py
from .models import Movies
from django import forms


class MoviesForm(forms.ModelForm):
    class Meta:
        model = Movies
        # fields = ["title", "url", "youtube_id"]
        fields = ["url"]
        labels = {"url": "YouTube Url:"}


class SearchForm(forms.Form):
    search_term = forms.CharField(max_length=255, label="Search for Videos:")

videos/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.forms import UserCreationForm
from django.http import Http404, JsonResponse
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views import generic
from videos.models import Row, Movies
from .forms import MoviesForm, SearchForm
from django.forms import formset_factory
import urllib
import requests
from django.forms.utils import ErrorList

YOUTUBE_API_KEY = ""


def home(request):
    recent_rows = Row.objects.all().order_by("-id")[:3]
    popular_rows = [Row.objects.get(pk=5), Row.objects.get(pk=4), Row.objects.get(pk=2)]
    return render(request, "videos/home.html", {"recent_rows": recent_rows, "popular_rows": popular_rows})


@login_required()
def dashboard(request):
    rows = Row.objects.filter(user=request.user)
    return render(request, "videos/dashboard.html", {"rows": rows})


class DeleteMovie(LoginRequiredMixin, generic.DeleteView):
    model = Movies
    template_name = "videos/delete_movie.html"
    success_url = reverse_lazy("dashboard")

    def get_object(self):
        movie = super(DeleteMovie, self).get_object()
        if not movie.row.user == self.request.user:
            raise Http404
        return movie


@login_required()
def movie_search(request):
    search_form = SearchForm(request.GET)
    if search_form.is_valid():
        encoded_search_term = urllib.parse.quote(search_form.cleaned_data["search_term"])
        response = requests.get(
            f"https://www.googleapis.com/youtube/v3/search?part=snippet&maxResults=6&q={encoded_search_term}&key={YOUTUBE_API_KEY}")
        return JsonResponse(response.json())
    return JsonResponse({"error": "Form not validated"})


def add_movie(request, pk):
    form = MoviesForm()
    # video_form_set = formset_factory(MoviesForm, extra=5)
    # form = video_form_set()

    search_form = SearchForm()
    row = Row.objects.get(pk=pk)
    if not row.user == request.user:
        raise Http404

    if request.method == "POST":
        form = MoviesForm(request.POST)
        # filled_form = video_form_set(request.POST)
        if form.is_valid():
            # loop for formset and + changes in html
            # for form in filled_form:
            movie = Movies()
            movie.row = row
            movie.url = form.cleaned_data["url"]
            # movie.title = filled_form.cleaned_data["title"]
            # movie.youtube_id = filled_form.cleaned_data["youtube_id"]
            parsed_url = urllib.parse.urlparse(movie.url)
            movie_id = urllib.parse.parse_qs(parsed_url.query).get("v")
            if movie_id:
                movie.youtube_id = movie_id[0]
                response = requests.get(
                    f"https://www.googleapis.com/youtube/v3/videos?part=snippet&id={movie_id[0]}&key={YOUTUBE_API_KEY}")
                json = response.json()
                title = json["items"][0]["snippet"]["title"]
                movie.title = title
                movie.save()
                return redirect("detail_row", pk)
            else:
                errors = form._errors.setdefault("url", ErrorList())
                errors.append("Needs to be youtube url")
    else:
        pass

    return render(request, "videos/add_movie.html", {"form": form, "search_form": search_form, "row": row})


class CreateRow(LoginRequiredMixin, generic.CreateView):
    model = Row
    fields = ["title"]
    template_name = "videos/create_row.html"
    success_url = reverse_lazy("dashboard")

    # adding user data to the form
    def form_valid(self, form):
        form.instance.user = self.request.user
        super(CreateRow, self).form_valid(form)
        return redirect("dashboard")


class DetailRow(generic.DetailView):
    model = Row
    template_name = "videos/detail_row.html"


class UpdateRow(LoginRequiredMixin, generic.UpdateView):
    model = Row
    template_name = "videos/update_row.html"
    fields = ["title"]
    success_url = reverse_lazy("dashboard")

    def get_object(self):
        row = super(UpdateRow, self).get_object()
        if not row.user == self.request.user:
            raise Http404
        return row


class DeleteRow(LoginRequiredMixin, generic.DeleteView):
    model = Row
    template_name = "videos/delete_row.html"
    success_url = reverse_lazy("dashboard")

    def get_object(self):
        row = super(DeleteRow, self).get_object()
        if not row.user == self.request.user:
            raise Http404
        return row


class SignUp(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy("dashboard")
    template_name = "registration/signup.html"

    # add automatic login after signup
    def form_valid(self, form):
        view = super(SignUp, self).form_valid(form)
        username, password = form.cleaned_data.get("username"), form.cleaned_data.get("password1"),
        user = authenticate(username=username, password=password)
        login(self.request, user)
        return view

videos/templates/videos/add_movie.html
{% extends "videos/base.html" %}

{% block content %}

    <div class="container">
        <div class="col-6 pt-3"><h2>Add Movie to {{ row.title }}</h2></div>
        <form method="post" id="submit_video">

            {% csrf_token %}
            {% load widget_tweaks %}

            {% for i in form %}
                <div class="col-6 form-group {% if i.errors %}alert alert-danger {% endif %}">
                    {{ i.errors }}
                    {#                    <b>{{ i.label_tag }}</b>#}
                    {% render_field i placeholder=i.label class="form-control" %}

                </div>
            {% endfor %}

            <div class="col-6">
                <button type="submit" class="btn btn-primary"> Add</button>
            </div>
        </form>
        <div class="col-6 pt-3">
            <h2>or find video on youtube:</h2>
        </div>

        <div class="col-6 form-group">
            <form>
                {% load widget_tweaks %}


                {% for i in search_form %}

                    {#                    <b>{{ i.label_tag }}</b>#}
                    {{ i.errors }}
                    {% render_field i placeholder=i.label class="form-control" %}


                {% endfor %}


            </form>
        </div>
        <div class="col-12" id="search_results">
            <script>
                var delayTimer;
                $("#id_search_term").keyup(function () {
                    clearTimeout(delayTimer);
                    $("#search_results").text("Loading...");
                    delayTimer = setTimeout(function () {
                        var text = $("#id_search_term").val();
                        $.ajax({
                            url: "/movie/search",
                            data: {
                                "search_term": text
                            },
                            dataType: "json",
                            success: function (data) {

                                var results = "";
                                $("#search_results").text("");

                                results += '<div class="row">';

                                data["items"].forEach(function (video) {
                                    results += '<div class="col-md-4 mt-3"><div class="card mb-4 shadow-sm">';
                                    results += '<iframe width="100%" height="225" src="https://www.youtube.com/embed/'
                                        + video["id"]["videoId"] +
                                        '" frameborder="0" allow="accelerometer; autoplay; encrypted-media; ' +
                                        'gyroscope; picture-in-picture" allowfullscreen></iframe>';
                                    results += '<div class="card-body"><p class="card-text">' + video["snippet"]["title"] + '</p>';

                                    results += '<a href="#" class="btn btn-primary" onclick="addVideo(\'' + video['id']['videoId'] + '\')">Add</a></div></div></div>';


                                });
                                results += '</div>';

                                $("#search_results").append(results);
                            },
                        });
                    }, 1000);
                });

                function addVideo(video_id) {
                    $("#id_url").val("https://www.youtube.com/watch?v=" + video_id);
                    $("#submit_video").submit();
                }


            </script>
        </div>

    </div>

{% endblock %}

videos/templates/videos/base.html
<!doctype html>
<html lang="en">
{% load static %}

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Best Videos on YouTube</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css"
          integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <link href="{% static "custom.css" %}" rel="stylesheet">
    <link rel="shortcut icon" type="image/png" href="{% static "favicon.ico" %}"/>
</head>

<body>
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 bg-white border-bottom shadow-sm">
    <h5 class="my-0 mr-md-auto font-weight-normal"><a href="{% url 'home' %}" class="text-dark">Best Videos on YouTube</a>
    </h5>
    <nav class="my-2 my-md-0 mr-md-3">
        {% if user.is_authenticated %}
            <a class="p-2 text-dark" href="{% url "dashboard" %}">Dashboard</a>
            <a class="p-2 text-dark" href="{% url "logout" %}">Log Out</a>
        {% else %}
            <a class="p-2 text-dark" href="{% url "login" %}">Log In</a>
        {% endif %}
    </nav>
    {% if user.is_authenticated == False %}
        <a class="btn btn-outline-primary" href="{% url "signup" %}">Sign up</a>
    {% endif %}
</div>
<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script
  src="https://code.jquery.com/jquery-3.4.1.min.js"
  integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
  crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>


{% block content %}

{% endblock %}


</body>

</html>

videos/templates/videos/create_row.html
{% extends "videos/base.html" %}

{% block content %}

    <div class="container">
        <div class="col-6">
            <h2>Create Collection</h2>
        </div>
        <form method="POST">
            {% csrf_token %}
            {% load widget_tweaks %}

            {% for i in form %}
                <div class="col-6 form-group {% if i.errors %}alert alert-danger {% endif %}">
                    {{ i.errors }}
                    {#                    <b>{{ i.label_tag }}</b>#}
                    {% render_field i placeholder=i.label class="form-control" %}

                </div>
            {% endfor %}


            <div class="col-6">
                <button type="submit" class="btn btn-primary"> Create</button>
            </div>
        </form>
    </div>

{% endblock %}

videos/templates/videos/dashboard.html
{% extends "videos/base.html" %}

{% block content %}

    <div class="container">
        <div class="text-center">
            <h1>{{ user.username }}'s Collections</h1>
            <a href="{% url "create_row" %}" class="btn btn-primary">Create Collection</a>
        </div>

        {% for row in rows %}
            <h3><a href="{% url "detail_row" row.id %}">{{ row.title }}</a></h3>

            <a href="{% url "delete_row" row.id %}" class="btn btn-danger">Delete</a>
            <a href="{% url "update_row" row.id %}" class="btn btn-primary">Edit</a>
            <a href="{% url "add_movie" row.id %}" class="btn btn-primary">Add video</a>

            <div class="row">

                {% for movie in row.movies_set.all %}

                    <div class="col-md-4 mt-3">
                        <div class="card mb-4 shadow-sm">
                            <iframe width="100%" height="225"
                                    src="https://www.youtube.com/embed/{{ movie.youtube_id }}"
                                    frameborder="0" allow="accelerometer; autoplay; encrypted-media; ' +
                    'gyroscope; picture-in-picture" allowfullscreen></iframe>
                            <div class="card-body"><p class="card-text">{{ movie.title }}</p>
                            </div>
                        </div>
                    </div>


                {% endfor %}
            </div>
        {% endfor %}


    </div>

{% endblock %}

videos/templates/videos/delete_movie.html
{% extends "videos/base.html" %}

{% block content %}

    <div class="container">
        <h2>Delete Movie: {{ movies.title }}?</h2>
        <form method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-danger"> Delete</button>
        </form>


        <div class="row">

            <div class="col-md-4 mt-3">
                <div class="card mb-4 shadow-sm">
                    <iframe width="100%" height="225" src="https://www.youtube.com/embed/{{ movies.youtube_id }}"
                            frameborder="0" allow="accelerometer; autoplay; encrypted-media; ' +
                    'gyroscope; picture-in-picture" allowfullscreen></iframe>
                    <div class="card-body"><p class="card-text">{{ movies.title }}</p>
                    </div>
                </div>
            </div>

        </div>

    </div>

{% endblock %}

videos/templates/videos/delete_row.html
{% extends "videos/base.html" %}

{% block content %}

    <div class="container">
    <div class="col-6">
     <h2>Delete Collection: {{ row.title }}?</h2>
        <form method="POST">
         {% csrf_token %}
         {{ form.as_p }}
            <button type="submit" class="btn btn-danger"> Delete Collection </button>
     </form>
    <br>
        <h4> Check Collection: <a href="{% url 'detail_row' row.id %}">{{ row.title }}</a> </h4>
    </div>
    </div>

{% endblock %}

videos/templates/videos/detail_row.html
{% extends "videos/base.html" %}

{% block content %}

    <div class="container">

        <h3><a href="{% url "detail_row" row.id %}">{{ row.title }}</a></h3>
        <h4>Collection made by: {{ row.user.username }}</h4>

        {% if user.id == row.user_id %}
            <a href="{% url "delete_row" row.id %}" class="btn btn-danger">Delete Collection</a>
            <a href="{% url "update_row" row.id %}" class="btn btn-primary">Edit</a>
            <a href="{% url "add_movie" row.id %}" class="btn btn-primary">Add video</a>
        {% endif %}
        <div class="row">

            {% for movie in row.movies_set.all %}

                <div class="col-md-4 mt-3">
                    <div class="card mb-4 shadow-sm">
                        <iframe width="100%" height="225"
                                src="https://www.youtube.com/embed/{{ movie.youtube_id }}"
                                frameborder="0" allow="accelerometer; autoplay; encrypted-media; ' +
                    'gyroscope; picture-in-picture" allowfullscreen></iframe>
                        <div class="card-body"><p class="card-text">{{ movie.title }}</p>
                            {% if user.id == row.user_id %}
                                <a href="{% url "delete_movie" movie.id %}" class="btn btn-danger">Delete Movie</a>
                            {% endif %}
                        </div>

                    </div>

                </div>


            {% endfor %}
        </div>


    </div>

{% endblock %}

videos/templates/videos/home.html
{% extends "videos/base.html" %}

{% block content %}
    <section class="jumbotron text-center">
        <div class="container">
        <h1>  Create Your own YouTube Collection</h1>
            <p class="lead text-muted"> Show us  best of the best videos</p>
            <a href="{% url "create_row" %}" class="btn btn-primary">Create Your Collection</a>
        </div>
    </section>

    <div class="container">
        <h1 class="text-center">Popular Collections</h1>

         {% for row in popular_rows %}
            <h3><a href="{% url "detail_row" row.id %}">{{ row.title }}</a></h3>

{#            <a href="{% url "delete_row" row.id %}" class="btn btn-danger">Delete</a>#}
{#            <a href="{% url "update_row" row.id %}" class="btn btn-primary">Edit</a>#}
{#            <a href="{% url "add_movie" row.id %}" class="btn btn-primary">Add video</a>#}

            <div class="row">

                {% for movie in row.movies_set.all %}

                    <div class="col-md-4 mt-3">
                        <div class="card mb-4 shadow-sm">
                            <iframe width="100%" height="225"
                                    src="https://www.youtube.com/embed/{{ movie.youtube_id }}"
                                    frameborder="0" allow="accelerometer; autoplay; encrypted-media; ' +
                    'gyroscope; picture-in-picture" allowfullscreen></iframe>
                            <div class="card-body"><p class="card-text">{{ movie.title }}</p>
                            </div>
                        </div>
                    </div>


                {% endfor %}
            </div>
        {% endfor %}

    <h1 class="text-center">Recent Collections</h1>

         {% for row in recent_rows %}
            <h3><a href="{% url "detail_row" row.id %}">{{ row.title }}</a></h3>

{#            <a href="{% url "delete_row" row.id %}" class="btn btn-danger">Delete</a>#}
{#            <a href="{% url "update_row" row.id %}" class="btn btn-primary">Edit</a>#}
{#            <a href="{% url "add_movie" row.id %}" class="btn btn-primary">Add video</a>#}

            <div class="row">

                {% for movie in row.movies_set.all %}

                    <div class="col-md-4 mt-3">
                        <div class="card mb-4 shadow-sm">
                            <iframe width="100%" height="225"
                                    src="https://www.youtube.com/embed/{{ movie.youtube_id }}"
                                    frameborder="0" allow="accelerometer; autoplay; encrypted-media; ' +
                    'gyroscope; picture-in-picture" allowfullscreen></iframe>
                            <div class="card-body"><p class="card-text">{{ movie.title }}</p>
                            </div>
                        </div>
                    </div>


                {% endfor %}
            </div>
        {% endfor %}

    </div>

{% endblock %}

videos/templates/videos/update_row.html
{% extends "videos/base.html" %}

{% block content %}

    <div class="container">
     <div class="col-6">
        <h2>Edit Collection</h2>
     </div>
        <form method="POST">
         {% csrf_token %}

            {% load widget_tweaks %}

            {% for i in form %}
                <div class="col-6 form-group {% if i.errors %}alert alert-danger {% endif %}">
                    {{ i.errors }}
                    {#                    <b>{{ i.label_tag }}</b>#}
                    {% render_field i placeholder=i.label class="form-control" %}

                </div>
            {% endfor %}
        <div class="col-6">
            <button type="submit" class="btn btn-primary"> Save </button>

        </form>

    <a href="{% url 'delete_row' row.id %}" class="btn btn-danger"> Delete Collection</a>
</div>
    </div>

{% endblock %}